- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-cdbdd7a2  # Redhat
      keypair: REDHAT # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: ""
         aws_secret_key: ""
         group: REDHAT  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Demo"
         instance_tags:
            Name: "Demo"
         vpc_subnet_id: "subnet-6dcf5a04"
         assign_public_ip: yes
      register: ec2
#boto required 
- debug:
    msg: "{{ ec2.instances }}"

